name: Windows - RustDesk test15

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 222
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/welgo5vswp67oj0a064me/Downloads.bat?rlkey=6ojzwxjwoj5qboyv8p9irzb6o&st=q30l03z9&dl=0" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To RustDesk
        run: cmd /c show.bat

      - name: Time Counter
        run: python time.py
